spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthire_application
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8085

application:
  integrations:
    document-service:
      base-url: http://localhost:8082
    job-service:
      base-url: http://localhost:8084
