spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smarthire_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: ${SERVER_PORT:8081}

security:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-before-production-change-this-secret-key}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}

auth:
  integrations:
    job-service:
      base-url: ${AUTH_INTEGRATIONS_JOB_SERVICE_BASE_URL:http://localhost:8084}
